# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 03:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('department_name', models.CharField(max_length=2048)),
                ('address', models.CharField(max_length=2048)),
                ('city', models.CharField(max_length=2048)),
                ('state', models.CharField(max_length=2048)),
                ('zipcode', models.IntegerField()),
                ('admin', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Clinical_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(default=0)),
                ('is_master', models.IntegerField(default=0)),
                ('is_starred', models.IntegerField(default=0)),
                ('param_count', models.IntegerField(default=0)),
                ('default_priority', models.IntegerField(default=0)),
                ('equation', models.CharField(max_length=2048)),
                ('get_param_sql', models.CharField(max_length=2048)),
                ('get_param', models.CharField(max_length=2048)),
                ('recommendation', models.CharField(max_length=2048)),
                ('updated_by', models.CharField(max_length=2048)),
                ('created_by', models.CharField(max_length=2048)),
                ('short_text', models.CharField(max_length=2048)),
                ('med_text', models.CharField(max_length=2048)),
                ('large_text', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('last_update', models.DateTimeField(verbose_name='date published')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Equation_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(default=0)),
                ('source_type', models.CharField(max_length=2048)),
                ('link', models.CharField(max_length=2048)),
                ('directive', models.CharField(max_length=2048)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Equation')),
            ],
        ),
        migrations.CreateModel(
            name='Subuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=2048)),
                ('password', models.CharField(max_length=2048)),
                ('first_name', models.CharField(max_length=2048)),
                ('middle_name', models.CharField(max_length=2048)),
                ('last_name', models.CharField(max_length=2048)),
                ('title', models.CharField(max_length=2048)),
                ('suffix', models.CharField(max_length=2048)),
                ('display_name', models.CharField(max_length=2048)),
                ('user_type', models.CharField(max_length=2048)),
                ('update_user', models.IntegerField()),
                ('created_user', models.IntegerField()),
                ('is_admin', models.IntegerField()),
                ('last_login', models.DateTimeField(verbose_name='date published')),
                ('last_update', models.DateTimeField(verbose_name='date published')),
                ('last_password_update', models.DateTimeField(verbose_name='date published')),
                ('highlighted', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='User_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.IntegerField(default=0)),
                ('sub_type', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=2048)),
                ('copied', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Equation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.FloatField()),
                ('description', models.CharField(max_length=2048)),
                ('user_priority', models.IntegerField(default=0)),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('last_update', models.DateTimeField(verbose_name='date published')),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Equation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('last_update', models.DateTimeField(verbose_name='date published')),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Equation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='subuser',
            name='parent_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
