# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='equation',
            name='created_by',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='equation',
            name='last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='equation',
            name='updated_by',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
